#!/usr/bin/env bash
# Copy Kenney assets from `.resources/` into `kenney_pack/` (paths must match KenneyPackPaths).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/.resources"
DST="$ROOT/kenney_pack"
if [ ! -d "$SRC" ]; then
	echo "Missing $SRC — place the Kenney all-in bundle there first." >&2
	exit 1
fi
mkdir -p "$DST"
mkdir -p "$DST/2D assets/Tiny Dungeon"
cp -a "$SRC/2D assets/Tiny Dungeon/." "$DST/2D assets/Tiny Dungeon/"
mkdir -p "$DST/2D assets/Scribble Platformer/PNG/Default"
cp -a "$SRC/2D assets/Scribble Platformer/PNG/Default/ui_circle.png" "$DST/2D assets/Scribble Platformer/PNG/Default/"
mkdir -p "$DST/2D assets/Tiny Town"
cp -a "$SRC/2D assets/Tiny Town/." "$DST/2D assets/Tiny Town/"
mkdir -p "$DST/2D assets/Topdown Tanks/PNG/Environment"
cp -a "$SRC/2D assets/Topdown Tanks/PNG/Environment/treeLarge.png" "$DST/2D assets/Topdown Tanks/PNG/Environment/"
mkdir -p "$DST/2D assets/RPG Urban Pack/Tilemap"
cp -a "$SRC/2D assets/RPG Urban Pack/Tilemap/tilemap_packed.png" "$DST/2D assets/RPG Urban Pack/Tilemap/"
mkdir -p "$DST/UI assets/UI Adventure Pack/PNG"
cp -a "$SRC/UI assets/UI Adventure Pack/PNG/panel_blue.png" "$SRC/UI assets/UI Adventure Pack/PNG/panelInset_blue.png" "$DST/UI assets/UI Adventure Pack/PNG/"
mkdir -p "$DST/Icons/Input Prompts/Keyboard & Mouse/Default"
cp -a "$SRC/Icons/Input Prompts/Keyboard & Mouse/Default/keyboard_e.png" "$DST/Icons/Input Prompts/Keyboard & Mouse/Default/"
mkdir -p "$DST/Icons/Input Prompts/Keyboard & Mouse/Double"
cp -a "$SRC/Icons/Input Prompts/Keyboard & Mouse/Double/"{keyboard_e,keyboard_j,keyboard_escape}.png "$DST/Icons/Input Prompts/Keyboard & Mouse/Double/"
mkdir -p "$DST/Icons/Input Prompts/Xbox Series/Double"
cp -a "$SRC/Icons/Input Prompts/Xbox Series/Double/"{xbox_button_color_x,xbox_button_color_a,xbox_button_start}.png "$DST/Icons/Input Prompts/Xbox Series/Double/"
mkdir -p "$DST/Audio/Music Jingles/Audio (Retro)"
cp -a "$SRC/Audio/Music Jingles/Audio (Retro)/"{jingles-retro_03,jingles-retro_06,jingles-retro_09,jingles-retro_12,jingles-retro_15}.ogg "$DST/Audio/Music Jingles/Audio (Retro)/"
mkdir -p "$DST/Audio/Interface Sounds/Audio"
cp -a "$SRC/Audio/Interface Sounds/Audio/"{select_003,confirmation_002,back_002,error_003,open_002,close_002,click_003,tick_001,tick_002}.ogg "$DST/Audio/Interface Sounds/Audio/"
mkdir -p "$DST/Audio/UI Audio/Audio"
cp -a "$SRC/Audio/UI Audio/Audio/mouseclick1.ogg" "$DST/Audio/UI Audio/Audio/"
mkdir -p "$DST/Audio/Music Loops/Loops"
cp -a "$SRC/Audio/Music Loops/Loops/Flowing Rocks.ogg" "$DST/Audio/Music Loops/Loops/"
mkdir -p "$DST/Audio/Music Loops/Retro"
cp -a "$SRC/Audio/Music Loops/Retro/Retro Mystic.ogg" "$DST/Audio/Music Loops/Retro/"
mkdir -p "$DST/Audio/RPG Audio/Audio"
cp -a "$SRC/Audio/RPG Audio/Audio/"{footstep04,doorOpen_2,doorClose_2,creak2}.ogg "$DST/Audio/RPG Audio/Audio/"
mkdir -p "$DST/Audio/Foley Sounds/Audio/Swords"
cp -a "$SRC/Audio/Foley Sounds/Audio/Swords/sword2.ogg" "$DST/Audio/Foley Sounds/Audio/Swords/"
mkdir -p "$DST/Audio/Impact Sounds/Audio"
cp -a "$SRC/Audio/Impact Sounds/Audio/"{footstep_grass_000,footstep_grass_001,footstep_grass_002}.ogg "$DST/Audio/Impact Sounds/Audio/"
echo "Synced into $DST"
